name: "Simply Add PR Label"
description: "A bot that looks at the last time EIPs were edited and marks them as withdrawn if they haven't been edited in a certain amount of time"
inputs:
  githubToken:
    description: |-
      The Github token to be used by this bot when creating branches, committing updated files, and open PRs
    required: true
  labelToAdd:
    description: |-
      this label is added to the PR
    required: true

runs:
  using: "composite"
  steps:
    - run: |-
        cd ${{github.action_path}} && yarn install && yarn build\
        && sh -c "sudo chmod -R 777 ./build"\
        && GITHUB_TOKEN=${{ inputs.GITHUB-TOKEN }} LABEL_TO_ADD=${{ inputs.labelToAdd }}\
        node build/src/index.js
      shell: bash
